Repository BKFP/R-Type, pull requests merged in 2023-12, with the labels that each got.

#2 Feat/CMake
  .gitignore
  CMakeLists.txt
  Doxyfile
  build.sh
  clean.sh
  client/CMakeLists.txt
  client/includes/client.hpp
  client/src/client.cpp
  documentation.sh
  server/CMakeLists.txt
  server/includes/server.hpp
  server/src/server.cpp
Labels: Set-up

#12 feat: basic ECS
  .gitignore
  Doxyfile
  engine/includes/ECS.hpp
  engine/includes/components.hpp
  engine/src/ECS.cpp
Labels: feature

#11 Doxygen update
  .gitignore
  clean.sh
  docs/Doxyfile
  docs/pages/dependencies.dox
  docs/pages/mainpage.dox
  documentation.sh
Labels: documentation

#21 Background Parallax Effect
  assets/background/Parallax100.png
  assets/background/Parallax60.png
  assets/background/Parallax80.png
  assets/sprites/r-typesheet1.gif
  assets/sprites/r-typesheet10.gif
  assets/sprites/r-typesheet11.gif
  assets/sprites/r-typesheet12.gif
  assets/sprites/r-typesheet13.gif
  assets/sprites/r-typesheet14.gif
  assets/sprites/r-typesheet16.gif
  assets/sprites/r-typesheet17.gif
  assets/sprites/r-typesheet18.gif
  assets/sprites/r-typesheet19.gif
  assets/sprites/r-typesheet2.gif
  assets/sprites/r-typesheet20.gif
  assets/sprites/r-typesheet21.gif
  assets/sprites/r-typesheet22.gif
  assets/sprites/r-typesheet23.gif
  assets/sprites/r-typesheet24.gif
  assets/sprites/r-typesheet25.gif
  assets/sprites/r-typesheet26.gif
  assets/sprites/r-typesheet27.gif
  assets/sprites/r-typesheet28.gif
  assets/sprites/r-typesheet29.gif
  assets/sprites/r-typesheet3.gif
  assets/sprites/r-typesheet30.gif
  assets/sprites/r-typesheet30a.gif
  assets/sprites/r-typesheet31.gif
  assets/sprites/r-typesheet32.gif
  assets/sprites/r-typesheet33.gif
  assets/sprites/r-typesheet34.gif
  assets/sprites/r-typesheet35.gif
  assets/sprites/r-typesheet36.gif
  assets/sprites/r-typesheet37.gif
  assets/sprites/r-typesheet38.gif
  assets/sprites/r-typesheet39.gif
  assets/sprites/r-typesheet40.gif
  assets/sprites/r-typesheet41.gif
  assets/sprites/r-typesheet42.gif
  assets/sprites/r-typesheet43.gif
  assets/sprites/r-typesheet44.gif
  assets/sprites/r-typesheet5.gif
  assets/sprites/r-typesheet7.gif
  assets/sprites/r-typesheet8.gif
  assets/sprites/r-typesheet9.gif
  client/includes/client.hpp
  client/src/client.cpp
Labels: feature

#28 Feat/network network protocol RFC documentation
  docs/pages/RFC_protocol.dox
  docs/pages/network_message_norm.dox
Labels: documentation

#30 Feat/client
  client/includes/client.hpp
  client/includes/network.hpp
  client/src/client.cpp
  client/src/main.cpp
  engine/includes/network.hpp
  server/includes/network.hpp
  server/includes/server.hpp
  server/src/server.cpp
Labels: feature

#38 Feat/GitHub pages
  .github/workflows/doxygen.yml
Labels: documentation, feature

#42 Graphical Encapsulation
  assets/background/parallax100.png
  assets/background/parallax60.png
  assets/background/parallax80.png
  client/CMakeLists.txt
  client/external/sfml.cpp
  client/external/sfml.hpp
  client/includes/client.hpp
  client/src/client.cpp
  client/src/main.cpp
Labels: feature
