Repository BKFP/R-Type, pull requests merged in 2024-01, with the labels that each got.

#52 Feat/network update data player
  client/external/sfml.cpp
  client/external/sfml.hpp
  client/includes/client.hpp
  client/includes/network.hpp
  client/src/main.cpp
  engine/includes/network.hpp
  engine/includes/network_library/boost_udp.hpp
  server/includes/network.hpp
  server/includes/server.hpp
  server/src/server.cpp
Labels: Set-up, feature

#55 fix(wbuild): wbuild now makes a dev and a release version
  wbuild.sh
Labels: bug

#72 feat(Keyboard): keys are now treated as a state rather than an event
  client/external/sfml.cpp
  client/external/sfml.hpp
  client/includes/client.hpp
  client/includes/keystates.hpp
  client/src/client.cpp
Labels: feature

#74 Feat/main menu
  assets/fonts/r-type-font.otf
  client/CMakeLists.txt
  client/external/sfml.cpp
  client/external/sfml.hpp
  client/src/client.cpp
  client/src/main.cpp
Labels: feature

#79 Menu & Settings Scene
  assets/background/outerSpace.png
  assets/background/spaceGarage.png
  client/external/sfml.cpp
  client/includes/keystates.hpp
  client/src/client.cpp
Labels: feature

#80 Background Parallax in Client
  client/external/sfml.cpp
  client/external/sfml.hpp
  client/includes/client.hpp
  client/src/client.cpp
Labels: feature

#81 Housekeeping
  client/CMakeLists.txt
  client/external/sfml/draw.cpp
  client/external/sfml/events.cpp
  client/external/sfml/sfml.cpp
  client/external/sfml/sfml.hpp
  client/external/sfml/textures.cpp
  client/includes/client.hpp
  client/src/client.cpp
  client/src/ecs.cpp
  client/src/inputs.cpp
  client/src/scenes/connection.cpp
  client/src/scenes/game.cpp
  client/src/scenes/gameOver.cpp
  client/src/scenes/mainMenu.cpp
  client/src/scenes/sceneManager.cpp
  client/src/scenes/settings.cpp
Labels: Set-up

#82 Add Music
  assets/sounds/effects/gameOver.ogg
  assets/sounds/music/mainTheme.ogg
  assets/sounds/music/stage1.ogg
  client/CMakeLists.txt
  client/external/sfml/assets.cpp
  client/external/sfml/draw.cpp
  client/external/sfml/sfml.hpp
  client/src/client.cpp
Labels: feature

#84 83 isolate igraphical
  client/external/sfml/sfml.hpp
  client/includes/IGraphical.hpp
  client/includes/client.hpp
Labels: Set-up

#92 Rendering entities
  client/includes/client.hpp
  client/src/ecs.cpp
  client/src/rendering.cpp
  client/src/scenes/game.cpp
  engine/includes/ECS.hpp
Labels: feature

#93 Engine improvements
  engine/includes/ECS.hpp
  engine/includes/components.hpp
Labels: feature

#97 add(INPUT): key rebinding, I do not condone the horrors I was forced …
  client/includes/client.hpp
  client/src/input.cpp
Labels: feature

#109 Parallax
  assets/background/parallax100.png
  assets/background/parallax60.png
  assets/background/sky.png
  client/external/sfml/assets.cpp
  client/includes/client.hpp
  client/src/client.cpp
  client/src/scenes/game.cpp
Labels: bug, feature

#110 Feat Shooting
  client/external/sfml/assets.cpp
  client/external/sfml/draw.cpp
  client/includes/client.hpp
  client/src/ecs.cpp
  client/src/input.cpp
  server/src/server.cpp
Labels: feature

#106 Update Documentation
  client/external/sfml/sfml.hpp
  client/includes/IGraphical.hpp
  client/includes/client.hpp
  client/includes/input.hpp
  client/src/input.cpp
  engine/includes/ECS.hpp
  engine/includes/components.hpp
  engine/includes/network.hpp
  engine/includes/network_library/boost_udp.hpp
  server/includes/levels.hpp
  server/includes/server.hpp
  server/src/init_entity.cpp
  server/src/levels.cpp
  server/src/server.cpp
Labels: documentation

#115 Enemies Factory
  client/external/sfml/assets.cpp
  client/external/sfml/draw.cpp
  client/src/ecs.cpp
  server/includes/enemies.hpp
  server/includes/levels.hpp
  server/includes/server.hpp
  server/levels/config_files/level_1.conf
  server/src/enemies.cpp
  server/src/levels.cpp
  server/src/server.cpp
Labels: feature

#124 Health Pack
  assets/background/healthPack.png
  client/external/sfml/assets.cpp
  engine/includes/components.hpp
  levels/config_files/level_1.conf
  levels/config_files/level_2.conf
  levels/config_files/level_3.conf
  server/includes/server.hpp
  server/src/levels.cpp
  server/src/server.cpp
Labels: feature

#127 Shooting Sound Effect
  assets/sounds/effects/shoot.ogg
  client/external/sfml/assets.cpp
  client/includes/client.hpp
  client/src/input.cpp
  server/src/levels.cpp
Labels: feature

#132 Bosses
  client/external/sfml/assets.cpp
  levels/config_files/level_1.conf
  levels/config_files/level_2.conf
  server/includes/enemies.hpp
Labels: feature
